<a href="https://colab.research.google.com/github/Shambhavi-Gupta/DL_Numpy-5/blob/master/DL_Numpy_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

In [ ]:
import numpy as np

In [ ]:
x = np.array([1 ,2 ,3])
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
l = [4 ,5 ,10]
x = np.asarray(l)
type(x
     )


numpy.ndarray

In [ ]:
x = np.asarray(l ,float)
print(x)

[ 4.  5. 10.]


In [ ]:
x.shape

(3,)

In [ ]:
x = np.array([[1 ,2 ,3] , [4 ,5 ,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x[0,0]

1

In [ ]:
x[1 ,2]

6

In [ ]:
x[0 ,0:2]

array([1, 2])

In [ ]:
x[0 ,:]

array([1, 2, 3])

In [ ]:
x = np.zeros((4 ,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x = np.eye(4 ,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x = np.random.random((4 ,5))
print(x)

[[0.19615532 0.84645808 0.24467871 0.99260754 0.39821636]
 [0.81735969 0.97431748 0.43113331 0.02145377 0.81281019]
 [0.13662673 0.26188086 0.13612996 0.36718988 0.3373753 ]
 [0.34989212 0.69903524 0.21139794 0.94512197 0.11846324]]


In [ ]:
z = x.T

In [ ]:
print(z)

[[0.19615532 0.81735969 0.13662673 0.34989212]
 [0.84645808 0.97431748 0.26188086 0.69903524]
 [0.24467871 0.43113331 0.13612996 0.21139794]
 [0.99260754 0.02145377 0.36718988 0.94512197]
 [0.39821636 0.81281019 0.3373753  0.11846324]]


In [ ]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
b = np.arange(5)

In [ ]:
c = a + b
d = a - b
e = a * b
print(c ,d ,e)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [ ]:
"""This is a concept of broadcasting in python"""
print(a , a+1)

[0 1 2 3 4] [1 2 3 4 5]


In [ ]:
a = np.floor(np.random.random((2 , 3))*10)
print(a)

[[9. 8. 6.]
 [8. 3. 3.]]


In [ ]:
u = [1 ,2 ,3]
v = [-1 ,0 ,1]
p1 = np.inner(u ,v)
print(p1)

2


In [ ]:
p2 = np.outer(u ,v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [ ]:
a = np.ones((2, 3))
b = np.ones((3, 2))
np.dot(a ,b)

array([[3., 3.],
       [3., 3.]])

In [ ]:
np.dot(b.T ,a.T)

array([[3., 3.],
       [3., 3.]])